name: Construir APK Android

on:
  push:
    branches:
      - main  # Asegúrate que tu rama principal se llame 'main' o 'master'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4  # <-- Actualizado a v4

      - name: Configurar Java
        uses: actions/setup-java@v4 # <-- Actualizado a v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # <-- Actualizado a v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Ionic CLI
        run: npm install -g @ionic/cli

      - name: Construir proyecto Ionic (Web)
        run: ionic build

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Dar permisos a Gradle
        run: chmod +x android/gradlew

      - name: Generar APK (Debug)
        run: cd android && ./gradlew assembleDebug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4  # <-- ¡AQUÍ ESTABA EL ERROR! Ahora es v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          compression-level: 0 # Opcional: hace la subida más rápida al no comprimir doble
