- name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- AQUÍ ESTÁ EL CAMBIO ---
      - name: Instalar dependencias
        run: npm install --legacy-peer-deps
      # ---------------------------

      - name: Instalar Ionic CLI
        run: npm install -g @ionic/cli
